services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      - /media:/srv
      - /media/filebrowser/db:/database
    restart: unless-stopped
