version: "3.8"

services:
  flaresolver:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolver
    restart: always

    ports:
      - "8191:8191"

    environment:
      - LOG_LEVEL=info

    volumes:
      - /srv/docker/flaresolver/data:/app/data
