services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    volumes:
      - /srv/docker/uptime-kuma/data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.rule=PathPrefix(`/kuma`)"
      - "traefik.http.routers.kuma.entrypoints=web"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.kuma-strip.stripprefix.prefixes=/kuma"
      - "traefik.http.routers.kuma.middlewares=kuma-strip"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
